var numero = new Number(7);
var numeroA = new Number(-55);
var numeroB = new Number(389);
var numeroC = new Number(1000);
var numeroD = new Number(3.1459);
var numeroE = new Number(-46.267);
console.log(numero, numeroA, numeroB, numeroC, numeroD, numeroE);
console.log(numero + numeroE);
console.log(numero * numeroB);
console.log(numeroC / numeroD);